### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'input_len'

### ISSUE THREAD

**Issue by gabrielosluz** [PKSHATechnology-Research/camphr#53]
Hello.
A few days ago I was using the lib normally with a data set that I prepared as well as the data suggested in the documentation. But today I started to receive this error that I cannot find the cause. I'm using the same dataset and they are jsonl for training and json for label, as the model asks. I also made sure that there is no error inside the dataset, with extra parentheses or something like that.
Do you have any idea what may be causing this error?
![error](https://user-images.githubusercontent.com/48336943/81464112-5e82b380-9195-11ea-92d9-1133b12decbb.PNG)

**Comment by tamuhey** [comment]
Hi, thank you for reporting the issue!

I could repro the bug, and I found it is caused by backward incompatibility of new version of transformers.
For now, please run the command inside your virtual env:

```
$ pip install -U transformers==2.8.0
```

I'm preparing to publish new version of camphr, which depends on transformers<=2.8, and you'll be able to get it via `pip` soon.

**Comment by tamuhey** [comment]
I've published a new version 0.5.23, which may solve your problem.
